spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: rkd
    password: rkd
  jpa: 
    hibernate:
      ddl-auto: update
eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defualtzone: http://localhost:8761/eureka/
      
